# -*- coding: utf-8 -*-
"""Employee Attrition

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QMXYVci7ZFdlYyw-HUKHFVt9mE9r4pUE

**Employee Attrition**
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

"""**`Importing File`**"""

df=pd.read_excel("Employee.xlsx")

"""**Understanding the Data**"""

df.head(5)

df.shape

df.info()

df.describe()

"""Missing values"""

df.isnull().sum()

"""**Checking Duplicate Values**"""

df.duplicated().sum()

"""What is the overall attrition rate?"""

total_employees= len(df)
left_employee= (df["Attrition"]== "Yes").sum()

attrition_rate= (left_employee/total_employees)*100
print(f"Overall Attrition Rate: {attrition_rate: .2f}%")

"""Which department has the highest attrition?



"""

attrition_counts= df[df["Attrition"]== "Yes"] ["Department"].value_counts()
print("--- Attrition Count by Department ---")
print(attrition_counts)

"""Does overtime relate to attrition?"""

pd.crosstab(df['OverTime'], df['Attrition'])

"""Does salary affect attrition?"""

df.groupby('Attrition')['Monthly_Income'].mean()

"""Does job satisfaction relate to attrition?"""

pd.crosstab(df["Job_Satisfaction"], df["Attrition"], normalize="index") * 100

"""Does distance from home relate to attrition?"""

df.groupby("Attrition")["Distance_From_Home"].mean()

"""Does lack of promotion relate to attrition?"""

pd.crosstab(df["Promotion_Last_5_Years"], df["Attrition"], normalize="index")*100

"""Department Attrition Rate"""

pd.crosstab(df["Department"], df["Attrition"], normalize="index")*100

"""Python Visualizations

Attrition distribution
"""

sns.countplot(data=df, x="Attrition")
plt.title("Overall Attrition Distribution")
plt.show()

"""Attrition by Department"""

sns.countplot(data=df, x="Department", hue="Attrition")
plt.title("Attrition by Department")
plt.show()

"""Attrition by Job Role"""

plt.figure(figsize=(10,5))
sns.countplot(data=df, x="Job_Role", hue="Attrition")
plt.xticks(rotation=45)
plt.title("Attrition by Job Role")
plt.show()

"""OverTime vs Attrition"""

pd.crosstab(df['OverTime'], df['Attrition'], normalize='index') * 100

"""Attrition By Overtime"""

sns.countplot(data=df, x="OverTime", hue="Attrition")
plt.title("Attrition by Overtime")
plt.show()

"""Attrition by Salary Band"""

df["Salary_Band"]= pd.qcut(df["Monthly_Income"], q=3, labels= ["Low", "Medium", "High"])
sns.countplot(data=df, x="Salary_Band", hue="Attrition")
plt.title("Attrition by Salary Band")
plt.show()

"""Attrition by Age Group"""

df["Age_Group"]= pd.cut(df["Age"], bins=[18, 30, 45, 65], labels=["18-30", "31-45","46+"])
sns.countplot(data=df, x="Age_Group", hue="Attrition")
plt.title("Attrition by Age Group")
plt.title("Attrition by Age Group")
plt.show()

"""Attrition by Job Satisfaction"""

sns.countplot(data=df, x="Job_Satisfaction", hue="Attrition")
plt.title("Attrition by Job Satisfaction")
plt.show()

"""Attrition by Years at Company"""

plt.figure(figsize=(10,4))
sns.histplot(data=df, x="Years_At_Company", hue="Attrition", multiple="stack", kde=True)
plt.title("Attrition by Years at Company")
plt.show()

"""Attrition by Work-Life Balance"""

sns.countplot(data=df, x="Work_Life_Balance", hue="Attrition")
plt.title("Attrition by Work-Life Balance")
plt.show()

"""Attrition by Promotion History"""

sns.countplot(data=df, x="Promotion_Last_5_Years", hue="Attrition")
plt.title("Attrition by Promotion History")
plt.show()

"""Report Analysis"""

!pip install ydata-profiling

from ydata_profiling import ProfileReport

profile = ProfileReport(df, title="Employee Attrition Workforce Analytics Report")

profile.to_notebook_iframe()